version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/gensim

    steps:
      - checkout

      - restore_cache:
          key: pip-cache

      - run:
          name: Apt install (for latex render)
          command: |
            sudo apt-get -yq update
            sudo apt-get -yq remove texlive-binaries --purge
            sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk

      - run:
          name: Basic installation (tox)
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install tox

      - run:
          name: Build documentation
          command: |
            source venv/bin/activate
            tox -e docs -vv

      - store_artifacts:
          path:  docs/src/_build
          destination: documentation

      - save_cache:
          key: pip-cache
          paths:
            - "~/.cache/pip"
            - "~/.ccache"
            - "~/.pip-cache"
